### ISSUE TITLE
Use variable bindings when including user-supplied data in SQL queries

### ISSUE THREAD

**Issue by asmecher** [lepidus/scieloSubmissionsReport#1]
Rather than using e.g.:
```
$results = $this->retrieve("SELECT * FROM my_table WHERE my_column = '{$myValue}';");
```
...it's better to bind the variable using the SQL tools for this, e.g.:
```
$results = $this->retrieve('SELECT * FROM my_table WHERE my_column = ?', [$myValue]);
```
This helps prevent SQL injections.

**Comment by JhonathanLepidus** [comment]
@asmecher We solved this problem in [this commit](https://github.com/lepidus/scieloSubmissionsReport/commit/0fe6bb81e41727fd368abfe9f3e64fdf6f2993ad).

**Comment by diegoabadan** [comment]
Thanks @asmecher !
